services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181


  kafka:
    image: bitnami/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,LOCAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://host.docker.internal:9092,LOCAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LOG_RETENTION_BYTES: -1
      KAFKA_CFG_LOG_RETENTION_HOURS: -1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "15555:8080"
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'

  postgres:
    image: postgres:13
    container_name: postgres
    mem_limit: 2g
    environment:
      POSTGRES_PASSWORD: folio_admin
      POSTGRES_USER: folio_admin
      POSTGRES_DB: okapi_modules
    command: -c max_connections=200 -c shared_buffers=512MB -c log_duration=on -c log_min_duration_statement=0ms -c shared_preload_libraries=pg_stat_statements -c jit=off
    ports:
      - 5432:5432

  expose-docker-on-2375:
    image: alpine/socat
    container_name: expose-docker-on-2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    restart: always

  #minio:
  #  image: 'minio/minio'
  #  command: server /data --console-address ":9001"
  #  ports:
  #    - 9000:9000
  #    - 9001:9001

  #createbuckets: # This container will terminate after running its commands to create a bucket in minio
  #  image: minio/mc
  #  depends_on:
  #    - minio
  #  entrypoint: >
  #    /bin/sh -c "
  #    /usr/bin/mc config host add myminio http://host.docker.internal:9000 minioadmin minioadmin;
  #    /usr/bin/mc rm -r --force myminio/example-bucket;
  #    /usr/bin/mc mb myminio/example-bucket;
  #    exit 0;
  #    "

  #okapi:
  #  image: 'folioci/okapi:latest'
  #  command: 'dev'
  #  ports:
  #    - 9130:9130
  #  environment: # be careful to leave a space character after every java option
  #    JAVA_OPTIONS: |-
  #      -Dhttp.port=9130
  #      -Dokapiurl=http://host.docker.internal:9130
  #      -Dstorage=postgres
  #      -Dpostgres_username=folio_admin
  #      -Dpostgres_password=folio_admin
  #      -Dpostgres_database=okapi_modules
  #      -Dpostgres_host=host.docker.internal
  #      -Dhost=host.docker.internal
  #      -Dport_end=9170
  #      -DdockerUrl=tcp://expose-docker-on-2375:2375
  #  depends_on:
  #    - postgres

  #elasticsearch:
  #  image: 'ghcr.io/zcube/bitnami-compat/elasticsearch:7.17.9'
  #  ports:
  #    - 9300:9300
  #    - 9200:9200
  #  environment:
  #    ELASTICSEARCH_PLUGINS:
  #      "analysis-icu,analysis-kuromoji,analysis-smartcn,analysis-nori,analysis-phonetic"
