spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/okapi_modules
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    openfeign:
      client:
        config:
          search:
            url: http://localhost:8085/search

management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers,env,httptrace,metrics,prometheus,beans
