spring:
  application:
    name: mod-linked-data
  server.port: 8081
  cloud:
    openfeign:
      okhttp:
        enabled: true
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  main:
    allow-bean-definition-overriding: true

folio:
  environment: ${ENV:folio}
  okapiUrl: ${okapi.url}
  logging:
    request:
      enabled: true
    feign:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers
      base-path: /admin
  endpoint:
    loggers:
      enabled: true
