spring:
  application:
    name: mod-linked-data
  server:
    port: 8081
  cloud:
    openfeign:
      okhttp:
        enabled: true
  datasource:
    username: folio
    password: QdA6j4QyrfDUwW4Vx80B9nBx
    url: jdbc:postgresql://localhost:5434/folio
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
    open-in-view: false

folio:
  environment: ${ENV:folio}
  okapiUrl: ${okapi.url}
  logging:
    request:
      enabled: true
    feign:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers,env,httptrace,metrics,prometheus
      base-path: /admin
  endpoint:
    loggers:
      enabled: true

mod-linked-data:
  default-schema: public
