spring:
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 5
        spring:
          json:
            add:
              type:
                headers=false:
