spring:
  application:
    name: mod-linked-data
  server:
    port: 8081
  cloud:
    openfeign:
      okhttp:
        enabled: true
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet.multipart.max-file-size: 50000KB
  servlet.multipart.max-request-size: 50000KB

management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers,env,httptrace,metrics,prometheus
      base-path: /admin
  endpoint:
    loggers:
      enabled: true

mod-linked-data:
  default-schema: public
  minio:
    endpoint: {MINIO_ENDPOINT}
    access-key: {MINIO_ACCESS_KEY}
    secret-key: {MINIO_SECRET_KEY}
