spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/okapi_modules
    username: folio_admin
    password: folio_admin
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    openfeign:
      client:
        config:
          search:
            url: http://localhost:9130/search

management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers,env,httptrace,metrics,prometheus,beans
