spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/folio
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    openfeign:
      client:
        config:
          search:
            url: http://localhost:8085/search
