openapi: 3.0.0
info:
  title: Folio modules API
  version: v2.1.0
  description: Folio modules API used by mod-linked-data

paths: {}

components:
  schemas:
    searchCreateIndexRequest:
      $ref: search/createIndexRequest.json
    searchCreateIndexResponse:
      $ref: search/folioCreateIndexResponse.json
    resourceIndexEvent:
      $ref: search/resourceIndexEvent.json
    resourceIndexEventType:
      $ref: search/resourceIndexEventType.json
    bibframe:
      $ref: search/bibframeIndex.json
    bibframeAuthority:
      $ref: search/bibframeAuthorityIndex.json
    dataImportEvent:
      $ref: events/dataImportEvent.json
    inventoryInstanceIngressEvent:
      $ref: inventory/instanceIngressEvent.json
