openapi: 3.0.0
info:
  title: Folio modules API
  version: v2.1.0
  description: Folio modules API used by mod-linked-data

paths: {}

components:
  schemas:
    createIndexRequest:
      $ref: folio-modules/search/createIndexRequest.json
    createIndexResponse:
      $ref: folio-modules/search/createIndexResponse.json
    resourceIndexEvent:
      $ref: folio-modules/search/resourceIndexEvent.json
    resourceIndexEventType:
      $ref: folio-modules/search/resourceIndexEventType.json
    linkedDataWork:
      $ref: folio-modules/search/linkedDataWork.json
    linkedDataAuthority:
      $ref: folio-modules/search/linkedDataAuthority.json
    instanceIngressEvent:
      $ref: folio-modules/inventory/instanceIngressEvent.json
    sourceRecordDomainEvent:
      $ref: folio-modules/srs/sourceRecordDomainEvent.json
    sourceRecordType:
      $ref: folio-modules/srs/sourceRecordType.json
