openapi: 3.0.0
info:
  title: Linked Data API
  version: v1
  description: Linked Data service API

paths:
  /resources:
    post:
      operationId: createResource
      description: Create a Resource record
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: schema/resourceCreateRequest.json
      responses:
        '200':
          description: Created Resource record
          content:
            application/json:
              schema:
                $ref: schema/resourceResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    get:
      operationId: getResourcesShortInfoPage
      description: Get page of resources short info
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Page of resources short info as json
          content:
            application/json:
              example: example/resourcesShortInfo.sample
              schema:
                $ref: schema/resourceShortInfoPage.json
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resources/{id}:
    get:
      operationId: getResourceById
      description: Get a Resource record by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Resource as json string
          content:
            application/json:
              schema:
                $ref: schema/resourceResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      operationId: Resource
      description: Update a Resource record by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            example: example/resourceUpdateRequest.sample
            schema:
              $ref: schema/resourceUpdateRequest.json
      responses:
        '200':
          description: Updated Resource record
          content:
            application/json:
              schema:
                $ref: schema/resourceResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      operationId: deleteResource
      description: Delete a Resource record by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Resource record deleted
        '404':
          description: No resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: Resource record id
      schema:
        type: integer
        format: int64
    x-okapi-tenant-header:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant header value
      schema:
        type: string
    pageNumber:
      name: pageNumber
      in: query
      required: false
      description: Page number for paginated endpoint, default is 0
      schema:
        type: integer
    pageSize:
      name: pageSize
      in: query
      required: false
      description: Page size for paginated endpoint, default is 100
      schema:
        type: integer

  schemas:
    errorResponse:
      $ref: schema/errors.json

  responses:
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example: examples/validationErrorResponse.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example: example/unknownError.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
