openapi: 3.0.0
info:
  title: Linked Data API
  version: v1
  description: Linked Data service API

paths:
  /bibframes:
    post:
      operationId: createBibframe
      description: Create a Bibframe record
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: schema/bibframeRequest.json
      responses:
        '200':
          description: Created Bibframe record
          content:
            application/json:
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    get:
      operationId: getBibframesShortInfoPage
      description: Get page of bibframes short info
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Page of bibframes short info as json
          content:
            application/json:
              example: example/bibframesShortInfo.sample
              schema:
                $ref: schema/bibframeShortInfoPage.json
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /bibframes/{id}:
    get:
      operationId: getBibframeById
      description: Get a Bibframe record by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Bibframe as json string
          content:
            application/json:
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      operationId: updateBibframe
      description: Update a Bibframe record by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            example: example/bibframeRequest.sample
            schema:
              $ref: schema/bibframeRequest.json
      responses:
        '200':
          description: Updated Bibframe record
          content:
            application/json:
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      operationId: deleteBibframe
      description: Delete a Bibframe record by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Bibframe record deleted
        '404':
          description: No bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: Bibframe record id
      schema:
        type: integer
        format: int64
    x-okapi-tenant-header:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant header value
      schema:
        type: string
    pageNumber:
      name: pageNumber
      in: query
      required: false
      description: Page number for paginated endpoint, default is 0
      schema:
        type: integer
    pageSize:
      name: pageSize
      in: query
      required: false
      description: Page size for paginated endpoint, default is 100
      schema:
        type: integer

  schemas:
    errorResponse:
      $ref: schema/errors.json

  responses:
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example: examples/validationErrorResponse.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example: example/unknownError.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
