openapi: 3.0.0
info:
  title: Linked Data API
  version: v1
  description: Linked Data service API

paths:
  /reindex:
    put:
      operationId: reindex
      description: Start the process of reindexing of resources in the database
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/full'
      responses:
        '204':
          description: Started the process of reindex
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resource:
    post:
      operationId: createResource
      description: Create a Resource
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: schema/resourceDto.json
      responses:
        '200':
          description: Created resource
          content:
            application/json:
              schema:
                $ref: schema/resourceDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    get:
      operationId: getResourceShortInfoPage
      description: Get page of resource short info
      parameters:
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Page of resource short info as json
          content:
            application/json:
              example: example/resourceShortInfo.sample
              schema:
                $ref: schema/resourceShortInfoPage.json
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resource/{id}:
    get:
      operationId: getResourceById
      description: Get a resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Resource as json string
          content:
            application/json:
              schema:
                $ref: schema/resourceDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      operationId: updateResource
      description: Update a resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            example: example/resourceRequest.sample
            schema:
              $ref: schema/resourceDto.json
      responses:
        '200':
          description: Updated resource
          content:
            application/json:
              schema:
                $ref: schema/resourceDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
         description: No resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      operationId: deleteResource
      description: Delete a resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Resource deleted
        '404':
          description: No resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /profile:
    get:
      operationId: getProfile
      description: Get profile
      responses:
        '200':
          description: Profile
          content:
            text/plain;charset=utf-8:
              schema:
                type: string
                example: example/profile.sample
        '404':
          description: No profile is found
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: Bibframe resource id
      schema:
        type: integer
        format: int64
    x-okapi-tenant-header:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant header value
      schema:
        type: string
    pageNumber:
      name: pageNumber
      in: query
      required: false
      description: Page number for paginated endpoint, default is 0
      schema:
        type: integer
    pageSize:
      name: pageSize
      in: query
      required: false
      description: Page size for paginated endpoint, default is 100
      schema:
        type: integer
    type:
      name: type
      in: query
      required: false
      description: 'Resource type, for example: http://bibfra.me/vocab/lite/Instance'
      example: 'http://bibfra.me/vocab/lite/Instance'
      schema:
        type: string
    full:
      name: full
      in: query
      required: false
      description: Reindex all records if true, otherwise only not indexed
      schema:
        type: boolean

  schemas:
    errorResponse:
      $ref: schema/error/errors.json

  responses:
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example: examples/validationErrorResponse.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example: example/unknownError.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
