openapi: 3.0.0
info:
  title: Linked Data API
  version: v1
  description: Linked Data service API

paths:

  /bibframes:
    post:
      operationId: createBibframe
      description: Create a Bibframe record
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            example: example/bibframeCreateRequest.sample
            schema:
              $ref: schema/bibframeCreateRequest.json
      responses:
        '200':
          description: Created Bibframe record
          content:
            application/json:
              example: examples/bibframeResponse.sample
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    get:
      operationId: getBibframesShortInfoPage
      description: Get page of bibframes short info
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Page of bibframes short info as json
          content:
            application/json:
              example: example/bibframesShortInfo.sample
              schema:
                $ref: schema/bibframeShortInfoPage.json
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /bibframes/{slug}:
    get:
      operationId: getBibframeBySlug
      description: Get a Bibframe record by slug
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/slug'
      responses:
        '200':
          description: Bibframe as json string
          content:
            application/json:
              example: example/bibframeResponse.sample
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No bibframe is found by slug
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      operationId: updateBibframe
      description: Update a Bibframe record by Slug
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/slug'
      requestBody:
        content:
          application/json:
            example: example/bibframeUpdateRequest.sample
            schema:
              $ref: schema/bibframeUpdateRequest.json
      responses:
        '200':
          description: Updated Bibframe record
          content:
            application/json:
              example: examples/bibframeResponse.sample
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No bibframe is found by slug
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      operationId: deleteBibframe
      description: Delete a Bibframe record by Slug
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/slug'
      responses:
        '204':
          description: Bibframe record deleted
        '404':
          description: No bibframe is found by slug
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'


  /search/indices/{index}:
    post:
      operationId: createIndex
      description: Create an index
      parameters:
        - $ref: '#/components/parameters/index'
      responses:
        '200':
          description: Created index
          content:
            application/json:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    get:
      operationId: getIndices
      description: Get existed indices
      parameters:
        - $ref: '#/components/parameters/index'
      responses:
        '200':
          description: Indices found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

components:
  parameters:
    slug:
      name: slug
      in: path
      required: true
      description: Bibframe record slug
      schema:
        type: string
    x-okapi-tenant-header:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant header value
      schema:
        type: string
    pageNumber:
      name: pageNumber
      in: query
      required: false
      description: Page number for paginated endpoint, default is 0
      schema:
        type: integer
    pageSize:
      name: pageSize
      in: query
      required: false
      description: Page size for paginated endpoint, default is 100
      schema:
        type: integer
    index:
      name: index
      in: path
      required: true
      description: index
      schema:
        type: string

  schemas:
    errorResponse:
      $ref: schema/errors.json

  responses:
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example: examples/validationErrorResponse.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example: example/unknownError.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
